### ISSUE TITLE
interpret commandline arguments CLIENT

### ISSUE THREAD

**Issue by lukasbraundev** [DHBW-FN-TIT20/verteilte-systeme-bbpss#2]
# Description
The Client is started using a commandline call with several arguements to specify the task he wants to execute

# Todo
Programm the Code to interpret the comandline args and write a documentation into the ReadMe on the available commandline arguements

**Comment by schuler-henry** [comment]
Requirements:
- A client is started with the following arguments:
  - --port (mandatory)
  - --server-port (mandatory)
  - --server-address (mandatory)
  - **one** of the following commands (multiple commands on one client is not supported)
    - --subscribe &lt;TOPIC1&gt; &lt;TOPIC2&gt; &lt;...&gt; (multiple topics can be subscribed)
    - --publish &lt;TOPIC&gt; &lt;MESSAGE&gt; (only one message can be published)
    - --list-topics
    - --get-topic-status &lt;TOPIC&gt; (only one status can be requested)
- The order of CLI arguments does not matter

```bash
./client --port 1234 --server-port 1212 --server-address 0.0.0.0 --subscribe T1 T2 T3
./client --port 1234 --server-port 1212 --server-address 0.0.0.0 --publish T1 M1
```
